"""Technical ticket analysis services."""

from dataclasses import dataclass

from app.db.models.ticket import Ticket, TicketPriority, TicketType
from app.services.repository import RepositoryReader, RepositorySnapshot


@dataclass(frozen=True)
class GeneratedTicketAnalysis:
    """Analysis generated by an impact analyzer."""

    complexity: str
    estimated_hours: int
    affected_files: list[str]
    risks: list[str]
    technical_summary: str
    recommended_tasks: list[str]
    proposed_changes: list[dict[str, str]]


class TicketImpactAnalyzer:
    """Interface for ticket impact analyzers."""

    async def analyze(self, ticket: Ticket) -> GeneratedTicketAnalysis:
        """Generate a technical impact analysis for a ticket."""
        raise NotImplementedError


class MockTicketImpactAnalyzer(TicketImpactAnalyzer):
    """Deterministic mock analyzer used until an external AI provider is enabled."""

    def __init__(self, repository_reader: RepositoryReader | None = None) -> None:
        self.repository_reader = repository_reader or RepositoryReader()

    async def analyze(self, ticket: Ticket) -> GeneratedTicketAnalysis:
        """Return a realistic simulated impact analysis."""
        complexity = self._complexity(ticket)
        estimated_hours = self._estimated_hours(ticket, complexity)
        repository_snapshot = await self.repository_reader.snapshot_for_company(
            ticket.company,
            f"{ticket.title}\n{ticket.description}",
        )
        affected_files = self._affected_files(ticket, repository_snapshot)

        return GeneratedTicketAnalysis(
            complexity=complexity,
            estimated_hours=estimated_hours,
            affected_files=affected_files,
            risks=self._risks(ticket),
            technical_summary=self._technical_summary(ticket, repository_snapshot),
            recommended_tasks=[
                "Revisar el alcance funcional con operaciones.",
                "Localizar modelos, servicios y endpoints afectados.",
                "Anadir o actualizar pruebas automatizadas de regresion.",
                "Preparar validacion QA con datos representativos.",
            ],
            proposed_changes=self._proposed_changes(ticket, affected_files, repository_snapshot),
        )

    def _complexity(self, ticket: Ticket) -> str:
        if ticket.priority is TicketPriority.URGENTE or ticket.type in {TicketType.HISTORIA_USUARIO, TicketType.BUG}:
            return "alta"
        if ticket.type in {TicketType.TAREA, TicketType.INCIDENCIA}:
            return "media"
        return "baja"

    def _estimated_hours(self, ticket: Ticket, complexity: str) -> int:
        base_hours = {"baja": 6, "media": 14, "alta": 28}[complexity]
        if ticket.priority is TicketPriority.URGENTE:
            base_hours += 8
        if len(ticket.description) > 500:
            base_hours += 6
        return base_hours

    def _affected_files(self, ticket: Ticket, repository_snapshot: RepositorySnapshot | None) -> list[str]:
        if repository_snapshot and repository_snapshot.candidate_files:
            return repository_snapshot.candidate_files

        common_files = [
            "app/api/routes/tickets.py",
            "app/services/ticket_service.py",
            "app/db/models/ticket.py",
            "tests/test_tickets.py",
        ]
        if ticket.type is TicketType.BUG:
            common_files.extend(["app/services/bug_triage.py", "tests/test_bug_triage.py"])
        if ticket.type is TicketType.HISTORIA_USUARIO:
            common_files.append("app/services/user_story_workflow.py")
        return common_files

    def _technical_summary(self, ticket: Ticket, repository_snapshot: RepositorySnapshot | None) -> str:
        base_summary = (
            f"El ticket '{ticket.title}' requiere revisar reglas de negocio, validaciones "
            "de datos y posibles efectos sobre flujos operativos."
        )
        if repository_snapshot is None:
            return f"{base_summary} No hay repositorio configurado para la empresa."
        if repository_snapshot.read_error:
            return (
                f"{base_summary} El repositorio configurado no se pudo leer desde la rama "
                f"'{repository_snapshot.branch}': {repository_snapshot.read_error}"
            )
        return (
            f"{base_summary} Se ha leido en modo solo lectura el repositorio "
            f"{repository_snapshot.repo_url} en la rama '{repository_snapshot.branch}' y se han localizado "
            f"{len(repository_snapshot.candidate_files)} archivos candidatos."
        )

    def _risks(self, ticket: Ticket) -> list[str]:
        risks = ["Cambios en validaciones pueden afectar tickets existentes."]
        if ticket.priority is TicketPriority.URGENTE:
            risks.append("La urgencia reduce margen para pruebas manuales exhaustivas.")
        if ticket.type is TicketType.BUG:
            risks.append("Debe reproducirse el bug antes de cerrar la correccion.")
        return risks

    def _proposed_changes(
        self,
        ticket: Ticket,
        affected_files: list[str],
        repository_snapshot: RepositorySnapshot | None,
    ) -> list[dict[str, str]]:
        branch = ticket.company.repo_branch if ticket.company and ticket.company.repo_branch else "rama pendiente"
        if repository_snapshot and repository_snapshot.read_error:
            return [
                {
                    "file": "repo_no_disponible",
                    "branch": repository_snapshot.branch,
                    "change": (
                        "No se ha podido leer el repositorio configurado. Revisa que la URL sea accesible, "
                        "que la rama exista y que el contenedor tenga salida a GitHub. "
                        "No se ha modificado ningun archivo."
                    ),
                },
            ]
        if repository_snapshot and affected_files:
            return [
                {
                    "file": file_path,
                    "branch": repository_snapshot.branch,
                    "change": (
                        "Archivo candidato detectado desde el repositorio real. Pendiente de desarrollar con "
                        "un proveedor IA: leer este fichero junto con la descripcion del ticket y proponer un diff "
                        "concreto en modo solo lectura."
                    ),
                }
                for file_path in affected_files[:5]
            ]
        return [
            {
                "file": "pendiente_de_conectar_repo",
                "branch": branch,
                "change": (
                    "Pendiente de desarrollar: todavia no hay repositorio conectado. Cuando se configure el repo, "
                    "la IA debera leer la rama indicada y la descripcion del ticket para proponer cambios concretos "
                    "sin modificar archivos automaticamente."
                ),
            },
        ]
